services:
  #  wiremock-standalone:
  #    image: wiremock/wiremock:3.11.0
  #    ports:
  #      - "8091:8080"
  #    volumes:
  #      - ./mappings:/home/wiremock/mappings
  #    networks:
  #      - poc-network

  wiremock:
    image: holomekc/wiremock-gui:3.13.157
    ports:
      - "${WIREMOCK_PORT:-8092}:8080"
      - "${WIREMOCK_HTTPS_PORT:-8443}:8443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - WIREMOCK_ARGS=--https-port=8443 --trust-all-proxy-targets --verbose
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-wiremock-stub}
      - OTEL_RESOURCE_ATTRIBUTES=service.name=${OTEL_SERVICE_NAME:-wiremock-stub},env=local
      - OTEL_LOGS_EXPORTER=${OTEL_ENABLED:+otlp}
      - OTEL_TRACES_EXPORTER=${OTEL_ENABLED:+otlp}
      - OTEL_METRICS_EXPORTER=${OTEL_ENABLED:+otlp}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - JAVA_TOOL_OPTIONS=${OTEL_ENABLED:+-javaagent:/home/libs/opentelemetry-javaagent.jar}
    volumes:
      - ${WIREMOCK_DATA_DIR:-./mocks}:/home/wiremock
      - ./libs:/home/libs
    networks:
      - poc-network

networks:
  poc-network:
    driver: bridge
