services:
  #  wiremock-standalone:
  #    image: wiremock/wiremock:3.11.0
  #    ports:
  #      - "8091:8080"
  #    volumes:
  #      - ./mappings:/home/wiremock/mappings
  #    networks:
  #      - poc-network

  wiremock:
    image: holomekc/wiremock-gui:3.13.157
    ports:
      - "${WIREMOCK_PORT:-8092}:8080"
      - "${WIREMOCK_HTTPS_PORT:-8443}:8443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: >
      --https-port 8443
      --https-keystore /home/wiremock/certificates/keystore.p12
      --keystore-password changeit
      --key-manager-password changeit
      --keystore-type PKCS12
      --https-truststore /home/wiremock/certificates/keystore.p12
      --truststore-password changeit
      --truststore-type PKCS12
      --https-require-client-cert
      ${WIREMOCK_VERBOSE_FLAG:---verbose}
    environment:
      - WIREMOCK_LOG_FILTER=${WIREMOCK_LOG_FILTER:-true}
      - OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME:-wiremock-service}
      - OTEL_RESOURCE_ATTRIBUTES=service.name=${OTEL_SERVICE_NAME:-wiremock-service},env=local
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4317
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - JAVA_TOOL_OPTIONS=-javaagent:/home/libs/stdout-redirect-agent.jar -javaagent:/home/libs/opentelemetry-javaagent.jar
    volumes:
      - ${WIREMOCK_DATA_DIR:-./mocks}:/home/wiremock
      - ./libs:/home/libs
      - ../../order-service/src/main/resources/certificates:/home/wiremock/certificates
    networks:
      - poc-network

networks:
  poc-network:
    driver: bridge
