spring:
  application:
    name: inventory-service

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  opentelemetry:
    resource-attributes:
      service.name: inventory-service
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} traceId=%X{traceId} spanId=%X{spanId} - %msg%n"
